# base configuration pulled from:
# https://github.com/dashbitco/broadway/blob/master/.github/workflows/ci.yml

name: Build & Publish

on:
  pull_request:
  push:
    branches:
      - "*"

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: "ubuntu-latest"

    services:
      postgres:
        # replace with `postgis/postgis:`, use dashes instead of dots for version
        image: postgres:15.3
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        elixir: ["1.15", "1.14", "1.13"]
        otp: ["26", "25"]
        exclude:
          - elixir: "1.13"
            otp: "26"
        include:
          - elixir: "1.15"
            otp: "26"
            coverage: coverage
            lint: lint
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Restore Dependency Cache
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: |
            mix-${{ runner.os }}-${{matrix.elixir}}-${{matrix.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{matrix.elixir}}-${{matrix.otp}}-

      - run: mix deps.get --only test
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: mix deps.compile --warnings-as-errors
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Check for unused deps
        run: mix deps.unlock --check-unused
        if: ${{matrix.lint}}

      - run: mix format --check-formatted
        if: ${{matrix.lint}}

      - name: Check for abandonded packaged
        run: mix hex.audit
        if: ${{matrix.lint}}

      - name: Set up database
        run: |
          PGPASSWORD=postgres psql -c 'create database postgres_test;' -U postgres -h localhost -p 5432

      - run: mix test

      - run: mix coveralls.github
        if: ${{matrix.lint}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        if: ${{matrix.lint}}
        id: changelog
        # uses: TriPSs/conventional-changelog-action@v4
        uses: iloveitaly/conventional-changelog-action@elixir-support
        with:
          github-token: ${{ secrets.github_token }}
          fallback-version: "0.1.0"
          version-file: "./mix.exs"
          output-file: "CHANGELOG.md"

      - name: Build & Publish
        run: |
          mix hex.build
          mix hex.publish --yes
        if: ${{matrix.lint && steps.changelog.outputs.skipped == 'false'}}
        env:
          MIX_ENV: dev
          # `gh secret set HEX_API_KEY --app actions --body $HEX_API_KEY`
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Github Release
        if: ${{ matrix.lint && steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
